version: '3.8'

services:
  test-apache2:
    build:
      args:
        user: laraveluser
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
    container_name: reto-day-1
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-reto100

  mysql:
      image: mysql:8.0
      container_name: laravel-db-reto-100
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: example_app
        MYSQL_ROOT_PASSWORD: db_root_password
        MYSQL_PASSWORD: db_password
        MYSQL_USER: db_user
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
      ports:
        - 3306:3306
      volumes:
        - dbretoslaravel100:/var/lib/mysql
      networks:
        - laravel-reto100

networks:
  laravel-reto100:
    driver: bridge
    
volumes:
 dbretoslaravel100: